//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Token.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TokenParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface ITokenVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrograma([NotNull] TokenParser.ProgramaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.funcoes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncoes([NotNull] TokenParser.FuncoesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.dec_funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDec_funcao([NotNull] TokenParser.Dec_funcaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.tipo_retorno"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo_retorno([NotNull] TokenParser.Tipo_retornoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo([NotNull] TokenParser.TipoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.tipo_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo_base([NotNull] TokenParser.Tipo_baseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.dimensao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimensao([NotNull] TokenParser.DimensaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametros([NotNull] TokenParser.ParametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.novo_parametro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNovo_parametro([NotNull] TokenParser.Novo_parametroContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.principal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrincipal([NotNull] TokenParser.PrincipalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloco([NotNull] TokenParser.BlocoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.dec_variaveis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDec_variaveis([NotNull] TokenParser.Dec_variaveisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.novo_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNovo_id([NotNull] TokenParser.Novo_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.comandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComandos([NotNull] TokenParser.ComandosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComando([NotNull] TokenParser.ComandoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.leitura"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeitura([NotNull] TokenParser.LeituraContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.escrita"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEscrita([NotNull] TokenParser.EscritaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermo([NotNull] TokenParser.TermoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.novo_termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNovo_termo([NotNull] TokenParser.Novo_termoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.selecao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelecao([NotNull] TokenParser.SelecaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.senao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSenao([NotNull] TokenParser.SenaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.enquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnquanto([NotNull] TokenParser.EnquantoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtribuicao([NotNull] TokenParser.AtribuicaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.complemento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplemento([NotNull] TokenParser.ComplementoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncao([NotNull] TokenParser.FuncaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.argumentos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentos([NotNull] TokenParser.ArgumentosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.novo_argumento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNovo_argumento([NotNull] TokenParser.Novo_argumentoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.retorno"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetorno([NotNull] TokenParser.RetornoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expressao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressao([NotNull] TokenParser.ExpressaoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_ou"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_ou([NotNull] TokenParser.Expr_ouContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_ou2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_ou2([NotNull] TokenParser.Expr_ou2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_e([NotNull] TokenParser.Expr_eContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_e2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_e2([NotNull] TokenParser.Expr_e2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_relacional([NotNull] TokenParser.Expr_relacionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_relacional2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_relacional2([NotNull] TokenParser.Expr_relacional2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_aditiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_aditiva([NotNull] TokenParser.Expr_aditivaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_aditiva2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_aditiva2([NotNull] TokenParser.Expr_aditiva2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.op_aditivo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_aditivo([NotNull] TokenParser.Op_aditivoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_multiplicativa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_multiplicativa([NotNull] TokenParser.Expr_multiplicativaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.expr_multiplicativa2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_multiplicativa2([NotNull] TokenParser.Expr_multiplicativa2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.op_multiplicativo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_multiplicativo([NotNull] TokenParser.Op_multiplicativoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFator([NotNull] TokenParser.FatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.vetor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVetor([NotNull] TokenParser.VetorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.constante"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstante([NotNull] TokenParser.ConstanteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TokenParser.sinal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinal([NotNull] TokenParser.SinalContext context);
}
