//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Token.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TokenParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface ITokenListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrograma([NotNull] TokenParser.ProgramaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrograma([NotNull] TokenParser.ProgramaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.funcoes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncoes([NotNull] TokenParser.FuncoesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.funcoes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncoes([NotNull] TokenParser.FuncoesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.dec_funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDec_funcao([NotNull] TokenParser.Dec_funcaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.dec_funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDec_funcao([NotNull] TokenParser.Dec_funcaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.tipo_retorno"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipo_retorno([NotNull] TokenParser.Tipo_retornoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.tipo_retorno"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipo_retorno([NotNull] TokenParser.Tipo_retornoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipo([NotNull] TokenParser.TipoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipo([NotNull] TokenParser.TipoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.tipo_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipo_base([NotNull] TokenParser.Tipo_baseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.tipo_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipo_base([NotNull] TokenParser.Tipo_baseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.dimensao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimensao([NotNull] TokenParser.DimensaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.dimensao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimensao([NotNull] TokenParser.DimensaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParametros([NotNull] TokenParser.ParametrosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParametros([NotNull] TokenParser.ParametrosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.novo_parametro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNovo_parametro([NotNull] TokenParser.Novo_parametroContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.novo_parametro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNovo_parametro([NotNull] TokenParser.Novo_parametroContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.principal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrincipal([NotNull] TokenParser.PrincipalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.principal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrincipal([NotNull] TokenParser.PrincipalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloco([NotNull] TokenParser.BlocoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.bloco"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloco([NotNull] TokenParser.BlocoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.dec_variaveis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDec_variaveis([NotNull] TokenParser.Dec_variaveisContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.dec_variaveis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDec_variaveis([NotNull] TokenParser.Dec_variaveisContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.novo_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNovo_id([NotNull] TokenParser.Novo_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.novo_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNovo_id([NotNull] TokenParser.Novo_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.comandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComandos([NotNull] TokenParser.ComandosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.comandos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComandos([NotNull] TokenParser.ComandosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComando([NotNull] TokenParser.ComandoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComando([NotNull] TokenParser.ComandoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.leitura"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeitura([NotNull] TokenParser.LeituraContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.leitura"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeitura([NotNull] TokenParser.LeituraContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.escrita"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEscrita([NotNull] TokenParser.EscritaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.escrita"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEscrita([NotNull] TokenParser.EscritaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermo([NotNull] TokenParser.TermoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermo([NotNull] TokenParser.TermoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.novo_termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNovo_termo([NotNull] TokenParser.Novo_termoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.novo_termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNovo_termo([NotNull] TokenParser.Novo_termoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.selecao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelecao([NotNull] TokenParser.SelecaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.selecao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelecao([NotNull] TokenParser.SelecaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.senao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSenao([NotNull] TokenParser.SenaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.senao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSenao([NotNull] TokenParser.SenaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.enquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnquanto([NotNull] TokenParser.EnquantoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.enquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnquanto([NotNull] TokenParser.EnquantoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtribuicao([NotNull] TokenParser.AtribuicaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.atribuicao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtribuicao([NotNull] TokenParser.AtribuicaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.complemento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplemento([NotNull] TokenParser.ComplementoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.complemento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplemento([NotNull] TokenParser.ComplementoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncao([NotNull] TokenParser.FuncaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.funcao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncao([NotNull] TokenParser.FuncaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.argumentos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentos([NotNull] TokenParser.ArgumentosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.argumentos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentos([NotNull] TokenParser.ArgumentosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.novo_argumento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNovo_argumento([NotNull] TokenParser.Novo_argumentoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.novo_argumento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNovo_argumento([NotNull] TokenParser.Novo_argumentoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.retorno"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetorno([NotNull] TokenParser.RetornoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.retorno"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetorno([NotNull] TokenParser.RetornoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expressao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressao([NotNull] TokenParser.ExpressaoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expressao"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressao([NotNull] TokenParser.ExpressaoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_ou"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_ou([NotNull] TokenParser.Expr_ouContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_ou"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_ou([NotNull] TokenParser.Expr_ouContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_ou2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_ou2([NotNull] TokenParser.Expr_ou2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_ou2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_ou2([NotNull] TokenParser.Expr_ou2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_e([NotNull] TokenParser.Expr_eContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_e"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_e([NotNull] TokenParser.Expr_eContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_e2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_e2([NotNull] TokenParser.Expr_e2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_e2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_e2([NotNull] TokenParser.Expr_e2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_relacional([NotNull] TokenParser.Expr_relacionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_relacional([NotNull] TokenParser.Expr_relacionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_relacional2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_relacional2([NotNull] TokenParser.Expr_relacional2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_relacional2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_relacional2([NotNull] TokenParser.Expr_relacional2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_aditiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_aditiva([NotNull] TokenParser.Expr_aditivaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_aditiva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_aditiva([NotNull] TokenParser.Expr_aditivaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_aditiva2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_aditiva2([NotNull] TokenParser.Expr_aditiva2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_aditiva2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_aditiva2([NotNull] TokenParser.Expr_aditiva2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.op_aditivo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_aditivo([NotNull] TokenParser.Op_aditivoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.op_aditivo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_aditivo([NotNull] TokenParser.Op_aditivoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_multiplicativa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_multiplicativa([NotNull] TokenParser.Expr_multiplicativaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_multiplicativa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_multiplicativa([NotNull] TokenParser.Expr_multiplicativaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_multiplicativa2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_multiplicativa2([NotNull] TokenParser.Expr_multiplicativa2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_multiplicativa2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_multiplicativa2([NotNull] TokenParser.Expr_multiplicativa2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.op_multiplicativo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_multiplicativo([NotNull] TokenParser.Op_multiplicativoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.op_multiplicativo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_multiplicativo([NotNull] TokenParser.Op_multiplicativoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFator([NotNull] TokenParser.FatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.fator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFator([NotNull] TokenParser.FatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.vetor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVetor([NotNull] TokenParser.VetorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.vetor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVetor([NotNull] TokenParser.VetorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.constante"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstante([NotNull] TokenParser.ConstanteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.constante"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstante([NotNull] TokenParser.ConstanteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.sinal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSinal([NotNull] TokenParser.SinalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.sinal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSinal([NotNull] TokenParser.SinalContext context);
}
