//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Token.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITokenListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class TokenBaseListener : ITokenListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrograma([NotNull] TokenParser.ProgramaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrograma([NotNull] TokenParser.ProgramaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.funcoes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncoes([NotNull] TokenParser.FuncoesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.funcoes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncoes([NotNull] TokenParser.FuncoesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.dec_funcao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDec_funcao([NotNull] TokenParser.Dec_funcaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.dec_funcao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDec_funcao([NotNull] TokenParser.Dec_funcaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.tipo_retorno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipo_retorno([NotNull] TokenParser.Tipo_retornoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.tipo_retorno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipo_retorno([NotNull] TokenParser.Tipo_retornoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipo([NotNull] TokenParser.TipoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipo([NotNull] TokenParser.TipoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.tipo_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipo_base([NotNull] TokenParser.Tipo_baseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.tipo_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipo_base([NotNull] TokenParser.Tipo_baseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.dimensao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDimensao([NotNull] TokenParser.DimensaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.dimensao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDimensao([NotNull] TokenParser.DimensaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.parametros"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParametros([NotNull] TokenParser.ParametrosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.parametros"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParametros([NotNull] TokenParser.ParametrosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.novo_parametro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNovo_parametro([NotNull] TokenParser.Novo_parametroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.novo_parametro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNovo_parametro([NotNull] TokenParser.Novo_parametroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.principal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrincipal([NotNull] TokenParser.PrincipalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.principal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrincipal([NotNull] TokenParser.PrincipalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloco([NotNull] TokenParser.BlocoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.bloco"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloco([NotNull] TokenParser.BlocoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.dec_variaveis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDec_variaveis([NotNull] TokenParser.Dec_variaveisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.dec_variaveis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDec_variaveis([NotNull] TokenParser.Dec_variaveisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.novo_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNovo_id([NotNull] TokenParser.Novo_idContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.novo_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNovo_id([NotNull] TokenParser.Novo_idContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.comandos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComandos([NotNull] TokenParser.ComandosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.comandos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComandos([NotNull] TokenParser.ComandosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.comando"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComando([NotNull] TokenParser.ComandoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.comando"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComando([NotNull] TokenParser.ComandoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.leitura"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeitura([NotNull] TokenParser.LeituraContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.leitura"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeitura([NotNull] TokenParser.LeituraContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.escrita"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEscrita([NotNull] TokenParser.EscritaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.escrita"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEscrita([NotNull] TokenParser.EscritaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermo([NotNull] TokenParser.TermoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermo([NotNull] TokenParser.TermoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.novo_termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNovo_termo([NotNull] TokenParser.Novo_termoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.novo_termo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNovo_termo([NotNull] TokenParser.Novo_termoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.selecao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelecao([NotNull] TokenParser.SelecaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.selecao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelecao([NotNull] TokenParser.SelecaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.senao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSenao([NotNull] TokenParser.SenaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.senao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSenao([NotNull] TokenParser.SenaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.enquanto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnquanto([NotNull] TokenParser.EnquantoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.enquanto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnquanto([NotNull] TokenParser.EnquantoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.atribuicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtribuicao([NotNull] TokenParser.AtribuicaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.atribuicao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtribuicao([NotNull] TokenParser.AtribuicaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.complemento"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplemento([NotNull] TokenParser.ComplementoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.complemento"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplemento([NotNull] TokenParser.ComplementoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.funcao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncao([NotNull] TokenParser.FuncaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.funcao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncao([NotNull] TokenParser.FuncaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.argumentos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentos([NotNull] TokenParser.ArgumentosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.argumentos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentos([NotNull] TokenParser.ArgumentosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.novo_argumento"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNovo_argumento([NotNull] TokenParser.Novo_argumentoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.novo_argumento"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNovo_argumento([NotNull] TokenParser.Novo_argumentoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.retorno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetorno([NotNull] TokenParser.RetornoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.retorno"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetorno([NotNull] TokenParser.RetornoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expressao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressao([NotNull] TokenParser.ExpressaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expressao"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressao([NotNull] TokenParser.ExpressaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_ou"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_ou([NotNull] TokenParser.Expr_ouContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_ou"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_ou([NotNull] TokenParser.Expr_ouContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_ou2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_ou2([NotNull] TokenParser.Expr_ou2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_ou2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_ou2([NotNull] TokenParser.Expr_ou2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_e([NotNull] TokenParser.Expr_eContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_e([NotNull] TokenParser.Expr_eContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_e2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_e2([NotNull] TokenParser.Expr_e2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_e2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_e2([NotNull] TokenParser.Expr_e2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_relacional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_relacional([NotNull] TokenParser.Expr_relacionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_relacional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_relacional([NotNull] TokenParser.Expr_relacionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_relacional2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_relacional2([NotNull] TokenParser.Expr_relacional2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_relacional2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_relacional2([NotNull] TokenParser.Expr_relacional2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_aditiva"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_aditiva([NotNull] TokenParser.Expr_aditivaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_aditiva"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_aditiva([NotNull] TokenParser.Expr_aditivaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_aditiva2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_aditiva2([NotNull] TokenParser.Expr_aditiva2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_aditiva2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_aditiva2([NotNull] TokenParser.Expr_aditiva2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.op_aditivo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_aditivo([NotNull] TokenParser.Op_aditivoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.op_aditivo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_aditivo([NotNull] TokenParser.Op_aditivoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_multiplicativa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_multiplicativa([NotNull] TokenParser.Expr_multiplicativaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_multiplicativa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_multiplicativa([NotNull] TokenParser.Expr_multiplicativaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.expr_multiplicativa2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_multiplicativa2([NotNull] TokenParser.Expr_multiplicativa2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.expr_multiplicativa2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_multiplicativa2([NotNull] TokenParser.Expr_multiplicativa2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.op_multiplicativo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp_multiplicativo([NotNull] TokenParser.Op_multiplicativoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.op_multiplicativo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp_multiplicativo([NotNull] TokenParser.Op_multiplicativoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFator([NotNull] TokenParser.FatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.fator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFator([NotNull] TokenParser.FatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.vetor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVetor([NotNull] TokenParser.VetorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.vetor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVetor([NotNull] TokenParser.VetorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.constante"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstante([NotNull] TokenParser.ConstanteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.constante"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstante([NotNull] TokenParser.ConstanteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TokenParser.sinal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSinal([NotNull] TokenParser.SinalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TokenParser.sinal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSinal([NotNull] TokenParser.SinalContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
